myproject/accounts/urls.py
from django.urls import path
from django.contrib.auth import login, logout
from .views import index, register, update_user, update_password

app_name = 'accounts'

urlpatterns = [
    path('', index, name='index'), 
    path('cadastro', register, name='register'),    
    path('alterar-dados/', update_user, name='update_user'),
    path('alterar-senha/', update_password, name='update_password'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('accounts/', include('myproject.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('coopervap/', include('myproject.coopervap.urls')),
    path('admin/', admin.site.urls),
]

myproject/accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )

    name = models.CharField('Nome', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

myproject/accounts/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User

        fields = [
            'username', 'email'
            ]


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff']

myproject/accounts/views.py
# coding=utf-8

from django.shortcuts import render
from django.views.generic import (
    CreateView, TemplateView, UpdateView, FormView
)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import login as auth_login
from .models import User
from .forms import UserAdminCreationForm


class IndexView(LoginRequiredMixin, TemplateView):

    template_name = 'accounts/index.html'


class RegisterView(CreateView):

    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('core:index')


class UpdateUserView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user
class UpdatePasswordView(LoginRequiredMixin, FormView):

    template_name = 'accounts/update_password.html'
    success_url = reverse_lazy('accounts:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

index = IndexView.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()
update_password = UpdatePasswordView.as_view()

myproject/accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block title %}Minha Conta{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'accounts:index' %}">Início</a></li>
  <li class="active">Minha Conta</li>
</ol>
<div class="row">
    <div class="col-md-4">
        <div class="list-group">
          <a href="{% url 'accounts:index' %}" class="list-group-item active">Minha Conta</a>
          <a href="{% url 'accounts:update_user' %}" class="list-group-item">Alterar Dados</a>
          <a href="{% url 'accounts:update_password' %}" class="list-group-item">Alterar Senha</a>
        {% if request.user.is_staff %}
          <a href="{% url 'accounts:register' %}" class="list-group-item">Criar usuario</a>
        {% endif %}
    
        </div>
    </div>
    <div class="col-md-8">
        {% block accounts_container %}
            <h2>Bem vindo {{ user}}</h2>
       {% endblock %}
    </div>
</div>
{% endblock %}

myproject/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Registro | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Registro</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

myproject/accounts/templates/accounts/update_password.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Senha{% endblock %}

{% block accounts_container %}
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

myproject/accounts/templates/accounts/update_user.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Dados{% endblock %}

{% block accounts_container %}
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

myproject/accounts/templates/accounts/update_user0.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Dados{% endblock %}

{% block accounts_container %}
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

myproject/accounts/templates/accounts/update_user1.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Dados{% endblock %}

{% block accounts_container %}
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}