myproject/coopervap/urls.py
from django.urls import path

from .views import index, cadcoopervap, cadcliente, clientelist, alterarcliente, ocliente, ochamado, relatorio, finalizando, pendentes, listafechado, chamado_funcionario

app_name = 'coopervap'

urlpatterns = [
    #chamados
    path('', index, name='index'),    
    path('ochamado/<int:pk>/', ochamado, name='ochamado'),
    path('relatorio/<int:pk>/', relatorio, name='relatorio'),
    path('finalizando/<int:pk>/', finalizando, name='finalizando'),    
    path('cadastro/', cadcoopervap, name='cadastro'),
    path('pendentes/', pendentes, name='pendentes'),
    path('fechado/', listafechado, name='listafechado'),
    #cliente
    path('quem-ligou/', cadcliente, name='cadcliente'),
    path('funcionarios/', clientelist, name='clientelist'),
    
    path('alterar-funcionario/<int:pk>/', alterarcliente, name='alterar-funcionario'),
    path('ocliente/<int:pk>/', ocliente, name='ocliente'),
    path('chamado-cliente/<int:item_id>/', chamado_funcionario, name='chamado_funcionario'),
  
] 

myproject/core/urls.py
from django.urls import path

from .forms import LoginForm
from myproject.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('dashboard/', v.dashboard, name='dashboard'),
    path('logout/', v.logout, name='logout'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('accounts/', include('myproject.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('coopervap/', include('myproject.coopervap.urls')),
    path('admin/', admin.site.urls),
]

myproject/coopervap/models.py
from django.db import models

from django.urls import reverse, reverse_lazy
from django.conf import settings


# Create your models here.
from myproject.accounts.models import User

#funcionarios da coopervap que ligam solicitando o suporte
class Cliente(models.Model):

    nome = models.CharField('Quem ligou', max_length=140)
    slug = models.SlugField('Identificador', max_length=100)
    ramal = models.CharField('Ramal', max_length=4, blank=True, null=True)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['nome']

    def __str__(self):
        return self.nome


class Ligacoes(models.Model):
    STATUS = (
        (0, 'Aberto'),
        (1, 'Aguardando'),
        (2, 'Cancelado'),
        (3, 'Pendente'),
        (5, 'Concluido'),
        (6, 'Encaminhado'),

    )
    #status do chamado
    data = models.DateField(null=True, auto_now_add=True)
    hora = models.TimeField(auto_now_add=True, blank=True) 
    situacao = models.IntegerField('Estado do chamado',choices=STATUS, default=0) 
    cliente = models.ForeignKey('coopervap.Cliente', verbose_name='Quem Ligou', on_delete=models.CASCADE)
    #adicionado o usuario que abriu o chamado como atendente
    atendente = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Atendente', on_delete=models.CASCADE)#, blank=True, null=True)    # ramal tem que pegar da classe cliente (que abre o chamado)
    assunto = models.TextField('Resumo do Problema')
    solucao = models.TextField('Descrição detalhada da solução', blank=True)
    tecnico = models.ForeignKey('accounts.User', verbose_name='Tecnico',null=True, blank=True, related_name='Tecnico', on_delete=models.CASCADE)
    #campo a ser pensado no aplicativo, seria a data ou hora do fechamento do chamado
    fechado = models.DateTimeField('Fechado em', blank=True, null=True, )

    # controle de modificacoes

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Chamado da Coopervap'
        verbose_name_plural = 'Chamados da Coopervap'

    # def __str__(self):
    #     return self.tipo or self.assunto

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

    def get_ordering(self, request):
        return [Lower('id')] 

    #def get_absolute_url(self):
        #return reverse('index', kwargs={'pk': self.pk})

myproject/coopervap/forms.py
from django.forms import ModelForm
from datetime import datetime
from django import forms
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.conf import settings
import datetime
from bootstrap_datepicker_plus import DateTimePickerInput
from .models import Ligacoes, Cliente

class LigacoesForm(ModelForm):


    class Meta:
        model = Ligacoes
        data = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
        fields = [
            #'num_chamado',
            'cliente', 'situacao', 'assunto', 'solucao'
             #'atendente'
            ]
class UpdateLigacoesForm(ModelForm):


    class Meta:
        model = Ligacoes
   
        
        fields = [
            'situacao', 'solucao','fechado', 'tecnico'
            ]
        widgets = {
       
            'fechado': DateTimePickerInput(format='%d/%m/%Y %H:%M'), # specify date-frmat
        }

class ClienteForm(forms.ModelForm):


    class Meta:
        model = Cliente
        fields = [
            'nome', 'slug', 'ramal',
            ]
#meu forms do problema do chamado cliente

class ChamadoClienteForm(ModelForm):

    class Meta:
        model = Ligacoes
        data = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
        fields = [
            #'num_chamado',
            'cliente',  'assunto', 'solucao'
            #'atendente'
        ]
        widgets = {
            # cria um combobox para os clientes escondido (display=none)
            'cliente': forms.Select(attrs={'display': 'none'}),
        }

myproject/coopervap/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    CreateView, TemplateView, UpdateView, FormView, ListView, DetailView
)
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.functions import Lower
from django.urls import reverse, reverse_lazy
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.db.models import Q
from django.conf import settings
from django.db import models
from fm.views import AjaxCreateView
from django.utils import timezone
#popup

from django.contrib.messages.views import SuccessMessageMixin
#gerar pdf
from easy_pdf.views import PDFTemplateView, PDFTemplateResponseMixin


# Create your views here.
from .models import Ligacoes, Cliente
from .forms import LigacoesForm, ClienteForm, ChamadoClienteForm, UpdateLigacoesForm

class IndexView(LoginRequiredMixin, ListView):

    model = Ligacoes
    template_name = 'coopervap/index.html'
    paginate_by = 100
       
    def get_queryset(self):
        queryset = Ligacoes.objects.all().order_by('-id')
        q = self.request.GET.get('q', '')
        if q:
            queryset = queryset.filter(
                models.Q(tipo__nome__icontains=q) | models.Q(
                    assunto__icontains=q)
                | models.Q(cliente__nome__icontains=q)
            )
        return queryset

    def get_context_data(self, **kwargs):
        pendentes = Ligacoes.objects.filter( Q(situacao = '0') | Q(situacao = '1' ) | Q(situacao = '2' ) | Q(situacao = '3' ) | Q(situacao = '6' ))
        total = pendentes.count()
        print ("Qtd pendentes:",total)
        context = super(IndexView, self).get_context_data(**kwargs)
        context['total'] = total
        return context

class LigacoesRegisterView(LoginRequiredMixin, CreateView):

    model = Ligacoes
    template_name = 'coopervap/register.html'
    form_class = LigacoesForm
    success_url = reverse_lazy('coopervap:index')

    def get_context_data(self, **kwargs):
        pendentes = Ligacoes.objects.filter( Q(situacao = '0') | Q(situacao = '1' ) | Q(situacao = '2' ) | Q(situacao = '3' ) | Q(situacao = '6' ))
        total = pendentes.count()
        print ("Qtd pendentes:",total)
        context = super(LigacoesRegisterView, self).get_context_data(**kwargs)
        context['total'] = total
        return context

    def post(self, request, *args, **kwargs):
            form = self.form_class(request.POST)
            if form.is_valid():


                form.revendedor = request.user
                obj = form.save(commit=False)
                obj.atendente = request.user
                
                obj.save()
                form.save()
                # <process form cleaned data>
                return HttpResponseRedirect(reverse('coopervap:index'))

            return render(request, self.template_name, {'form': form})

class PendenteListView(LoginRequiredMixin, ListView):

    model = Ligacoes
    template_name = 'coopervap/pendente.html'

    def get_context_data(self, **kwargs):
        pendentes = Ligacoes.objects.filter( Q(situacao = '0') | Q(situacao = '1' ) | Q(situacao = '2' ) | Q(situacao = '3' ) | Q(situacao = '6' ))
        total = pendentes.count()
        print ("Qtd pendentes:",total)
        context = super(PendenteListView, self).get_context_data(**kwargs)
        context['total'] = total
        return context


    def get_queryset(self):
        pendentes = Ligacoes.objects.filter( Q(situacao = '0') | Q(situacao = '1' ) | Q(situacao = '2' ) | Q(situacao = '3' ) | Q(situacao = '6' ))
        return pendentes

class FechadoListView(LoginRequiredMixin, ListView):

    model = Ligacoes
    template_name = 'coopervap/listafechado.html'

    def get_context_data(self, **kwargs):
        pendentes = Ligacoes.objects.filter( Q(situacao = '0') | Q(situacao = '1' ) | Q(situacao = '2' ) | Q(situacao = '3' ) | Q(situacao = '6' ))
        total = pendentes.count()
        print ("Qtd pendentes:",total)
        context = super(FechadoListView, self).get_context_data(**kwargs)
        context['total'] = total
        return context


    def get_queryset(self):
        return Ligacoes.objects.filter(situacao = '5')

class LigacoesDetailView(LoginRequiredMixin, DetailView):

    template_name = "coopervap/ochamado.html"

    def get_queryset(self):
        return Ligacoes.objects.filter()

class PdfDetailView(PDFTemplateResponseMixin, DetailView):
    model = Ligacoes 
    template_name = 'coopervap/pdf.html'

class LigacoesUpdateView(LoginRequiredMixin, UpdateView):

    model = Ligacoes
    template_name = 'coopervap/fechado.html'
    form_class = UpdateLigacoesForm
    success_url = reverse_lazy('core:index')

class TodosListView(LoginRequiredMixin, ListView):
    #lista todos os chamados
    model = Ligacoes
    template_name = 'coopervap/index-todos.html'
    #paginate_by = 10

    def get_queryset(self):
        return Ligacoes.objects.all().order_by('-id')

#app de cliente (funcionario da coopervap)
class ClienteList(LoginRequiredMixin, ListView):

    model = Cliente
    template_name = 'coopervap/func/index.html'
    # paginate_by = 100

    def get_context_data(self, **kwargs):
        pendentes = Ligacoes.objects.filter( Q(situacao = '0') | Q(situacao = '1' ) | Q(situacao = '2' ) | Q(situacao = '3' ) | Q(situacao = '6' ))
        total = pendentes.count()
        print ("Qtd pendentes:",total)
        context = super(FechadoListView, self).get_context_data(**kwargs)
        context['total'] = total
        return context

    # def get_context_data(self, **kwargs):
    #     qtdchamadoscli = Ligacoes.objects.filter(cliente__id=self.kwargs.get('pk'))
    #     totalchamadocli = qtdchamadoscli
    #     print("Qtd pendentes:", totalchamadocli)
    #     context = super(ClienteList, self).get_context_data(**kwargs)
    #     context['totalchamadocli'] = totalchamadocli
    #     return context

    def get_queryset(self):
        return Cliente.objects.all().order_by('-id')

class ClienteRegisterView(CreateView):

    model = Cliente
    template_name = 'coopervap/func/register.html'
    form_class = ClienteForm
    success_url = reverse_lazy('core:index')


class ClienteUpdateView(LoginRequiredMixin, UpdateView):

    model = Cliente
    template_name = 'coopervap/func/update.html'
    form_class = ClienteForm
    # fields = ['situacao', 'solucao']
    success_url = reverse_lazy('core:index')


class ClienteDetailView(LoginRequiredMixin, DetailView):

    template_name = "coopervap/func/ocliente.html"

    def get_queryset(self):
        return Cliente.objects.filter()

    def get_context_data(self, **kwargs):
        qtdchamadoscli = Ligacoes.objects.filter(cliente__id = self.kwargs.get('pk') )
        totalchamadocli = qtdchamadoscli
        print ("Qtd pendentes:",totalchamadocli)
        context = super(ClienteDetailView, self).get_context_data(**kwargs)
        context['totalchamadocli'] = totalchamadocli
        return context


#aqui e onde esta meu problema
class ChamadodoClienteRegisterView(FormView):

    model = Ligacoes
    template_name = 'coopervap/func/registerbyfunc.html'
    form_class = ChamadoClienteForm
    success_url = reverse_lazy('core:index')

    # class ChamadodoClienteRegisterView(CreateView):
    def get_context_data(self, **kwargs):
        # testando se o id da url é passado para esse contexto
        func_id = self.kwargs.get('item_id')
        teste_id = Cliente.objects.get(id=func_id)
        print("O id e: ", func_id, "e o outro e: ", teste_id.id)
        context = super(ChamadodoClienteRegisterView, self).get_context_data(**kwargs)
        # inicia o 'combobox cliente' com o usuario logado
        context['funcionario'] = self.form_class(initial={'cliente': Cliente.objects.get(id=func_id)})
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.atendente = request.user
            obj.save()
            form.save()
            # <process form cleaned data>
            return HttpResponseRedirect(reverse('core:index'))

        return render(request, self.template_name, {'form': form})
#chamado
index = IndexView.as_view()
cadcoopervap = LigacoesRegisterView.as_view()
ochamado = LigacoesDetailView.as_view()
relatorio = PdfDetailView.as_view()
finalizando = LigacoesUpdateView.as_view()
pendentes = PendenteListView.as_view()
listafechado = FechadoListView.as_view()
#cliente
cadcliente = ClienteRegisterView.as_view()
clientelist = ClienteList.as_view()
alterarcliente = ClienteUpdateView.as_view()
ocliente = ClienteDetailView.as_view()
chamado_funcionario = ChamadodoClienteRegisterView.as_view()

myproject/coopervap/templates/coopervap/func/index.html
{% extends "base.html" %}
{% load static %}

{% block container %}

  <div class="row">
    <div class="col-md-12">
      <div class="col-6 col-lg-5">
          
                {% include "includes/coopervap-pendentes.html" %}
                <h4 class="text-center text-uppercase">Lista de Funcionários </h4>

      {% include "includes/menucoopervap.html" %}
      <div class="card">

        <div class="card-body">
          <div class="row">
            <div class="col-sm-12">
              <div class="row">
                <div class="col-sm-12">
                  <div class="callout callout-info">
                    <small class="text-muted">
                        <div class="row">
                            <div class="col-lg-12">
                                <table id="table" class="display table-bordered text-left"  cellspacing="1" width="100%" >
                                    <thead>
                                        <tr><b>
                                            <th class="text-center">ID</th>
                                            <th class="text-center">Nome</th>
                                            <th class="text-center">Apelido</th>
                                            <th class="text-center">Ramal</th>
                                            

                                            <th class="text-center">Ações</th></b>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    {% for item in object_list %}
                                    <tr>
                                            <td>{{ item.id }}</td>
                                            <td><a href="#}"></a>{{ item.nome }}</a></td>
                                            <td>{{ item.slug }}</td>
                                            <td>{{ item.ramal }}</td>
                                            

                                            <td class="text-left">
                                                    <a href="{% url 'coopervap:ocliente' item.pk %}" class="btn">
                                                        <i class="fas fa-eye"></i>
                                                    </a>
                                                    <a href="{% url 'coopervap:alterar-funcionario' item.pk %}" class="btn">
                                                        <i class="fas fa-edit"></i>
                                                    </a>
                                                    <a href="{% url 'coopervap:chamado_funcionario' item.pk %}" class="btn">

                                                        <i class="fas fa-plus"></i>
                                                    </a>

                                            </td>
                                            </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>


                    </div>
                       {% include "includes/js-base.html" %}
                    </small>
                    <br>

                    <div class="chart-wrapper">
                      <canvas id="sparkline-chart-1" width="100" height="30"></canvas>
                    </div>
                  </div>
                </div>
              </div>
              <hr class="mt-0">
            </div>
          </div>

          <br/>

      </div>
    </div>
  </div>
{% endblock container %}

myproject/coopervap/templates/coopervap/func/ocliente.html
{% extends "base.html" %}
{% load static %}

{% block container %}

  <div class="row">
    <div class="col-md-12">
      <div class="col-6 col-lg-5">

                {% include "includes/coopervap-pendentes.html" %}

      {% include "includes/menucoopervap.html" %}
           <h3 class="text-center"><b>Funcionario Coopervap</b></h3>
<div class="container position-relative">
    <div class="row">
        <div class="col-md-4">
            <p><b> Nome</b> {{ cliente.nome}}</p>
            <p><b> Indentificador</b> {{ cliente.slug}}</p>
        </div>
        <div class="col-md-4">
            <p><b>Setor:</b> mercado</p>
            <p><b>Ramal:</b> {{ cliente.ramal }}</p>

        </div>
        <div class="col-md-4">
            <p><b>Quantidade de chamados desse funcionario:</b> {{ totalchamadocli.count}}</p>


        </div>
    </div>
</div>




    <h4 class="text-center">Lista de chamado do usuario</h4>
      <div class="card">

        <div class="card-body">
          <div class="row">

            <div class="col-sm-12">
              <div class="row">
                <div class="col-sm-12">
                  <div class="callout callout-info">
                    <small class="text-muted">
                        <div class="row">

                            <div class="col-lg-12">
                                <table id="table" class="display table-bordered text-left"  cellspacing="1" width="100%" >
                                    <thead>
                                        <tr><b>
                                            <th class="text-center">ID</th>
                                            <th class="text-center">Categoria</th>
                                            <th class="text-center">Status</th>
                                            <th class="text-center">Descrição</th>
                                            <th class="text-center">Data</th>
                                            <th class="text-center">Setor</th>
                                            <th class="text-center">Ações</th></b>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    {% for item in totalchamadocli %}
                                    <tr>
                                            <td>{{ item.id }}</td>
                                            <td>{{ item.tipo }}</td>
                                            {% if item.situacao == 5 %}
                                                    <td><span class="badge badge-success">{{ item.get_situacao_display }}</span></td>
                                                {% elif  item.situacao == 1  %}
                                                    <td><span class="badge badge-warning">{{ item.get_situacao_display }}</span></td>
                                                {% elif item.situacao == 3  %}
                                                    <td><span class="badge badge-danger">{{ item.get_situacao_display }}</span></td>
                                                {% elif item.situacao == 2  %}
                                                    <td><span class="badge badge-danger">{{ item.get_situacao_display }}</span></td>
                                                {% elif item.situacao == 6  %}
                                                    <td><span class="badge badge-warning">{{ item.get_situacao_display }}</span></td>
                                                {% elif item.situacao == 0  %}
                                                    <td><span class="badge badge-danger">{{ item.get_situacao_display }}</span></td>
                                                {% else %}
                                                    <td><p><span class="badge badge-danger">Status Invalido</span></p></td>
                                            {% endif %}
                                            <td>
                                                <a href="{% url 'coopervap:ochamado' item.pk %}"></a>{{ item.assunto }}</a>
                                            </td>
                                            <td>{{ item.data }}</td>
                                            <td>{{ item.cliente.setor }}</td>
                                            <td class="text-left">
                                                    <a href="{% url 'coopervap:ochamado' item.pk %}" class="btn">
                                                        <i class="fas fa-eye"></i>
                                                    </a>


                                                    <a href="{% url 'coopervap:finalizando' item.pk %}" class="btn">
                                                        <i class="fas fa-edit"></i></a>
                                            </td>
                                            </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>

<a class="btn btn-info btn-lg" href="{% url 'core:index' %}" role="button">Voltar</a>
                    </div>
                       {% include "includes/js-base.html" %}
                    </small>
                    <br>

                    <div class="chart-wrapper">
                      <canvas id="sparkline-chart-1" width="100" height="30"></canvas>
                    </div>
                  </div>
                </div>
              </div>
              <hr class="mt-0">
            </div>
          </div>

          <br/>

      </div>
    </div>
  </div>
{% endblock container %}

myproject/coopervap/templates/coopervap/func/qtdchamadocliente.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %} Funcionario da Coopervap| {{ block.super }}{% endblock %}

{% block container %}

<div class="jumbotron">

   <h1><b>Funcionario Coopervap</b></h1>

  <p><b> Nome</b> {{ cliente.nome}}</p>
  <p><b> Indentificador</b> {{ cliente.slug}}</p>
  <p><b>Setor:</b> {{ cliente.setor }}</p>
  <p><b>Ramal:</b> {{ cliente.ramal }}</p>
  <p><b>Quantidade de chamados desse funcionario:</b> {{ totalchamadocli.count}}</p>
    {% for item in object_list %}
     <p><b> ID</b> {{ item.id}}</p>
     <p><b> Assunto</b> {{ item.assunto}}</p>
      {% endfor %}


    <ol class="breadcrumb">


        <li><a class="btn btn-success btn-lg" href="{% url 'core:index' %}" role="button">Voltar</a></li>

</ol>

  

</div>
{% endblock %}

myproject/coopervap/templates/coopervap/func/register.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Cadastro de funcionario | {{ block.super }}{% endblock %}

{% block container %}
  <div class="row">
    <div class="col-md-12">
      <div class="col-6 col-lg-5">
          {% include "includes/coopervap-pendentes.html" %}

      {% include "includes/menucoopervap.html" %}
      <div class="card">

        <div class="card-body">
          <div class="row">
            <div class="col-sm-12">
              <div class="row">
                <div class="col-sm-12">
                  <div class="callout callout-info">
                    <small class="text-muted">
                        <h2><p> Cadastro de funcionario</p></h2>
                             <form role="form" method="post">

                                    {% csrf_token %}
                                    {% include 'includes/bs4_form.html' with form=form %}
                                    <div class="row">
                                        {% include 'includes/salvar.html'%}
                                    </div>
                              </form>
                    </small>
                    <br>

                    <div class="chart-wrapper">
                      <canvas id="sparkline-chart-1" width="100" height="30"></canvas>
                    </div>
                  </div>
                </div>
              </div>
              <hr class="mt-0">
            </div>
          </div>

          <br/>

      </div>
    </div>
  </div>
{% endblock container %}

myproject/coopervap/templates/coopervap/func/registerbyfunc.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Cadastro de funcionario | {{ block.super }}{% endblock %}

{% block container %}
  <div class="row">
    <div class="col-md-12">
      <div class="col-6 col-lg-5">
          {% include "includes/coopervap-pendentes.html" %}

      {% include "includes/menucoopervap.html" %}
      <div class="card">

        <div class="card-body">
          <div class="row">
            <div class="col-sm-12">
              <div class="row">
                <div class="col-sm-12">
                  <div class="callout callout-info">
                    <small class="text-muted">
                        <h2><p> Chamado do funcionario </p></h2><br>
                        {% if messages %}
                          <ul class="messages">
                            {% for message in messages %}
                              <li class="{{ message.tags }}">{{ message }}</li>
                            {% endfor %}
                          </ul>
                        {% endif %}
                             <form id="func_id" role="form" method="POST">

                                    {% csrf_token %}
                                    {% include 'includes/bs4_form.html' with form=funcionario %}
                                    <div class="row">
                                        {% include 'includes/salvar.html'%}
                                    </div>
                              </form>
                    </small>
                    <br>

                    <div class="chart-wrapper">
                      <canvas id="sparkline-chart-1" width="100" height="30"></canvas>
                    </div>
                  </div>
                </div>
              </div>
              <hr class="mt-0">
            </div>
          </div>

          <br/>

      </div>
    </div>
  </div>
{% endblock container %}

myproject/coopervap/templates/coopervap/func/update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Chamado da Coopervap | {{ block.super }}{% endblock %}

{% block container %}
  <div class="row">
    <div class="col-md-12">
      <div class="col-6 col-lg-5">
          {% include "includes/coopervap-pendentes.html" %}

      {% include "includes/menucoopervap.html" %}
      <div class="card">
       
        <div class="card-body">
          <div class="row">
            <div class="col-sm-12">
              <div class="row">
                <div class="col-sm-12">
                  <div class="callout callout-info">
                    <small class="text-muted">
                        <h2><p> Alterar dados do funcionario!</p></h2>
                             <form role="form" action="#" method="post">

                                    {% csrf_token %}
                                    {% include 'includes/bs4_form.html' with form=form %}
                                 <div class="row">
                                     {% include 'includes/salvar.html'%}
                                 </div>


                              </form>
                    </small>
                    <br>
                    
                    <div class="chart-wrapper">
                      <canvas id="sparkline-chart-1" width="100" height="30"></canvas>
                    </div>
                  </div>
                </div>
              </div>
              <hr class="mt-0">
            </div>
          </div> 
          
          <br/>
         
      </div>
    </div>
  </div>
{% endblock container %}